export const SEND_SMS = "SEND_SMS"
export const AUTH_ERROR = "AUTH_ERROR"
export const GOOGLE_LOGIN = "GOOGLE_LOGIN"
export const REGISTER = "REGISTER"
export const LOGIN = "LOGIN"
export const SET_ALERT = "SET_ALERT"
export const REMOVE_ALERT = "REMOVE_ALERT"
export const TOKEN_AUTH = "TOKEN_AUTH"
